FROM python:slim-buster
RUN mkdir -p /nodemingle
RUN apt update
RUN apt install -y build-essential
RUN pip install multicast_expert colander loguru click
ADD * /nodemingle/

# Set user and group
ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user} # <--- the '-m' create a user home directory
# RUN useradd -u ${uid} -s /bin/sh -m ${user} # <--- the '-m' create a user home directory

# Switch to user
USER ${uid}:${gid}

WORKDIR /nodemingle