apiVersion: batch/v1
kind: Job
metadata:
  name: rankn
spec:
  template:
    spec:
      containers:
      - name: rankn
        image: nodemingle:v0.1
        command: ["python","mingle.py","--sessionid=ThatsMe","--rankN"]
      restartPolicy: OnFailure