apiVersion: batch/v1
kind: Job
metadata:
  name: rank00
spec:
  template:
    spec:
      containers:
      - name: rank00
        image: nodemingle:v0.1
        command: ["python","mingle.py","--sessionid=ThatsMe","--rank0"]
      restartPolicy: OnFailure
